name: Build & Push Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      tag: placeholder

    steps:
    - uses: actions/checkout@v2

    - name: Set Tag
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: pthomison
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pthomison/tailscale:${{env.tag}}