name: Build & Push Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pthomison/tailscale:$(date +%s)
    - name: Push the Docker image
      run: docker push pthomison/tailscale:$(date +%s)